export enum CivitAiBaseModel {
  StableDiffusion1_4 = "SD 1.4",
  StableDiffusion1_5 = "SD 1.5",
  StableDiffusion1_5_LCM = "SD 1.5 LCM",
  StableDiffusion2_0 = "SD 2.0",
  StableDiffusion2_0_768 = "SD 2.0 768",
  StableDiffusion2_1 = "SD 2.1",
  StableDiffusion2_1_768 = "SD 2.1 768",
  StableDiffusion2_1_Unclip = "SD 2.1 Unclip",
  SDXL_0_9 = "SDXL 0.9",
  SDXL_1_0 = "SDXL 1.0",
  Pony = "Pony",
  SDXL_1_0_LCM = "SDXL 1.0 LCM",
  SDXL_Distilled = "SDXL Distilled",
  SDXL_Turbo = "SDXL Turbo",
  SDXL_Lightning = "SDXL Lightning",
  StableCascade = "Stable Cascade",
  SVD = "SVD",
  SVD_XT = "SVD XT",
  PlaygroundV2 = "Playground V2",
  PixArtA = "PixArt A",
  Other = "Other",
}
